site_name: Manual UDEC Universidad de Cundinamarca
theme:
  palette:
    primary: green
    accent: yellow
  logo: assets/logo.png
  favicon: assets/logo.png
  features:
    - navigation.instant
    - navigation.instant.prefetch
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - search.suggest
    - search.highlight
    - search.share
  language: es
  name: material
site_url: https://morasdefresa.github.io/UdecCampusManual
plugins:
  - search
  - tags:
      tags_file: tags.md
nav:
  - Bienvenido:
      - Acerca de: index.md
      - Campus virtual: campusVirtualTridimensional/campus_unity.md
  - Categorias: tags.md
  - Aspirante:
      - Estudia con nosotros: aspirante/estudia_nosotros.md
      - Soporte Aspirante: aspirante/soporte_aspirante.md
  - Apoyo Académico: apoyo_academico.md
  - Bienestar:
      - Menu Principal: bienestar/menu_bienestar.md
      - Calendario de Memorias: bienestar/calendario_bienestar.md
      - Galeria de arte: bienestar/galeria_arte_bienestar.md
      - Contenido Informativo:
          - Actividad Fisica: bienestar/contenidoInformativo/actividad_fisica_contenido_bienestar.md
          - Alimentación: bienestar/contenidoInformativo/alimentacion_contenido_bienestar.md
          - Cultural: bienestar/contenidoInformativo/cultural_contenido_bienestar.md
          - Productividad: bienestar/contenidoInformativo/productividad_contenido_bienestar.md
          - Salud: bienestar/contenidoInformativo/salud_contenido_bienestar.md
  - Comunidad / Networking:
      - Calendario Academico: networking/calendario_ucundinamarca.md
      - Chat UDEC: networking/chat_ucundinamarca.md
      - Foros UDEC: networking/foro_ucundinamarca.md
  - Estudiante:
      - Carnet Estudiantil: estudiante/carnet_estudiante.md
      - Horario: estudiante/horario_estudiante.md
      - Pagos:
          - Fraccionar Matricula: estudiante/pagos/fraccionar_matricula_estudiante.md
          - Recibos de pago: estudiante/pagos/recibos_estudiante.md
      - Perfil:
          - Avatar: estudiante/perfil/avatar_estudiante.md
  - Notificaciones: notificaciones.md
markdown_extensions:
  - attr_list
  - md_in_html
  - pymdownx.blocks.caption
